
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = [
  "github.com/tidwall/lotsa", 
  "github.com/mmcloughlin/geohash", 
  "github.com/tidwall/evio"
]

[[constraint]]
  branch = "master"
  name = "github.com/tidwall/tinybtree"

[[constraint]]
  branch = "master"
  name = "github.com/tidwall/boxtree"

[[constraint]]
  name = "github.com/tidwall/geojson"
  version = "1.1.0"

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.13.0"

[[constraint]]
  name = "github.com/eclipse/paho.mqtt.golang"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/peterh/liner"

[[constraint]]
  branch = "master"
  name = "github.com/gomodule/redigo"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[[constraint]]
  branch = "master"
  name = "github.com/tidwall/btree"

[[constraint]]
  branch = "master"
  name = "github.com/tidwall/buntdb"

[[constraint]]
  name = "github.com/tidwall/gjson"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/tidwall/redbench"

[[constraint]]
  branch = "master"
  name = "github.com/tidwall/redcon"

[[constraint]]
  branch = "master"
  name = "github.com/tidwall/resp"

[[constraint]]
  name = "github.com/tidwall/sjson"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.6.0"
